<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Auth.proto

namespace Auth\RegisterResponse;

use UnexpectedValueException;

/**
 * Protobuf type <code>auth.RegisterResponse.ResultCode</code>
 */
class ResultCode
{
    /**
     * Generated from protobuf enum <code>SUCCESS = 0;</code>
     */
    const SUCCESS = 0;
    /**
     * Generated from protobuf enum <code>FAILED = 1;</code>
     */
    const FAILED = 1;
    /**
     * Generated from protobuf enum <code>USERNAME_EXISTS = 2;</code>
     */
    const USERNAME_EXISTS = 2;
    /**
     * Generated from protobuf enum <code>EMAIL_EXISTS = 3;</code>
     */
    const EMAIL_EXISTS = 3;
    /**
     * Generated from protobuf enum <code>INVALID_PARAMS = 4;</code>
     */
    const INVALID_PARAMS = 4;

    private static $valueToName = [
        self::SUCCESS => 'SUCCESS',
        self::FAILED => 'FAILED',
        self::USERNAME_EXISTS => 'USERNAME_EXISTS',
        self::EMAIL_EXISTS => 'EMAIL_EXISTS',
        self::INVALID_PARAMS => 'INVALID_PARAMS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResultCode::class, \Auth\RegisterResponse_ResultCode::class);

