<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Auth.proto

namespace Auth;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 心跳请求
 *
 * Generated from protobuf message <code>auth.HeartbeatRequest</code>
 */
class HeartbeatRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 client_time = 1;</code>
     */
    protected $client_time = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $client_time
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 client_time = 1;</code>
     * @return int|string
     */
    public function getClientTime()
    {
        return $this->client_time;
    }

    /**
     * Generated from protobuf field <code>int64 client_time = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClientTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->client_time = $var;

        return $this;
    }

}

