<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Auth.proto

namespace Auth;

if (false) {
    /**
     * This class is deprecated. Use Auth\LoginResponse\ResultCode instead.
     * @deprecated
     */
    class LoginResponse_ResultCode {}
}
class_exists(LoginResponse\ResultCode::class);
@trigger_error('Auth\LoginResponse_ResultCode is deprecated and will be removed in the next major release. Use Auth\LoginResponse\ResultCode instead', E_USER_DEPRECATED);

