<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Auth.proto

namespace Auth;

if (false) {
    /**
     * This class is deprecated. Use Auth\RegisterResponse\ResultCode instead.
     * @deprecated
     */
    class RegisterResponse_ResultCode {}
}
class_exists(RegisterResponse\ResultCode::class);
@trigger_error('Auth\RegisterResponse_ResultCode is deprecated and will be removed in the next major release. Use Auth\RegisterResponse\ResultCode instead', E_USER_DEPRECATED);

