<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Auth.proto

namespace Auth;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 用户信息
 *
 * Generated from protobuf message <code>auth.UserInfo</code>
 */
class UserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>string username = 2;</code>
     */
    protected $username = '';
    /**
     * Generated from protobuf field <code>string nickname = 3;</code>
     */
    protected $nickname = '';
    /**
     * Generated from protobuf field <code>string email = 4;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>int32 level = 5;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>int64 exp = 6;</code>
     */
    protected $exp = 0;
    /**
     * Generated from protobuf field <code>int64 coins = 7;</code>
     */
    protected $coins = 0;
    /**
     * Generated from protobuf field <code>int32 vip_level = 8;</code>
     */
    protected $vip_level = 0;
    /**
     * Generated from protobuf field <code>repeated int32 unlocked_avatars = 9;</code>
     */
    private $unlocked_avatars;
    /**
     * Generated from protobuf field <code>int64 register_time = 10;</code>
     */
    protected $register_time = 0;
    /**
     * Generated from protobuf field <code>int64 last_login_time = 11;</code>
     */
    protected $last_login_time = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_id
     *     @type string $username
     *     @type string $nickname
     *     @type string $email
     *     @type int $level
     *     @type int|string $exp
     *     @type int|string $coins
     *     @type int $vip_level
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $unlocked_avatars
     *     @type int|string $register_time
     *     @type int|string $last_login_time
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nickname = 3;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * Generated from protobuf field <code>string nickname = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 4;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 level = 5;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>int32 level = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 exp = 6;</code>
     * @return int|string
     */
    public function getExp()
    {
        return $this->exp;
    }

    /**
     * Generated from protobuf field <code>int64 exp = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExp($var)
    {
        GPBUtil::checkInt64($var);
        $this->exp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 coins = 7;</code>
     * @return int|string
     */
    public function getCoins()
    {
        return $this->coins;
    }

    /**
     * Generated from protobuf field <code>int64 coins = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCoins($var)
    {
        GPBUtil::checkInt64($var);
        $this->coins = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 vip_level = 8;</code>
     * @return int
     */
    public function getVipLevel()
    {
        return $this->vip_level;
    }

    /**
     * Generated from protobuf field <code>int32 vip_level = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setVipLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->vip_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 unlocked_avatars = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnlockedAvatars()
    {
        return $this->unlocked_avatars;
    }

    /**
     * Generated from protobuf field <code>repeated int32 unlocked_avatars = 9;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnlockedAvatars($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->unlocked_avatars = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 register_time = 10;</code>
     * @return int|string
     */
    public function getRegisterTime()
    {
        return $this->register_time;
    }

    /**
     * Generated from protobuf field <code>int64 register_time = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRegisterTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->register_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 last_login_time = 11;</code>
     * @return int|string
     */
    public function getLastLoginTime()
    {
        return $this->last_login_time;
    }

    /**
     * Generated from protobuf field <code>int64 last_login_time = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastLoginTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_login_time = $var;

        return $this;
    }

}

