<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Auth.proto

namespace Auth\LoginResponse;

use UnexpectedValueException;

/**
 * Protobuf type <code>auth.LoginResponse.ResultCode</code>
 */
class ResultCode
{
    /**
     * Generated from protobuf enum <code>SUCCESS = 0;</code>
     */
    const SUCCESS = 0;
    /**
     * Generated from protobuf enum <code>FAILED = 1;</code>
     */
    const FAILED = 1;
    /**
     * Generated from protobuf enum <code>INVALID_CREDENTIALS = 2;</code>
     */
    const INVALID_CREDENTIALS = 2;
    /**
     * Generated from protobuf enum <code>USER_LOCKED = 3;</code>
     */
    const USER_LOCKED = 3;

    private static $valueToName = [
        self::SUCCESS => 'SUCCESS',
        self::FAILED => 'FAILED',
        self::INVALID_CREDENTIALS => 'INVALID_CREDENTIALS',
        self::USER_LOCKED => 'USER_LOCKED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResultCode::class, \Auth\LoginResponse_ResultCode::class);

