<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SlotGame.proto

namespace Slot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 客户端消息
 *
 * Generated from protobuf message <code>slot.ClientMessage</code>
 */
class ClientMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * JOIN_ROOM, LEAVE_ROOM, SPIN, BUY_BONUS
     *
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>string player_id = 2;</code>
     */
    protected $player_id = '';
    /**
     * Generated from protobuf field <code>string room_id = 3;</code>
     */
    protected $room_id = '';
    /**
     * Generated from protobuf field <code>int64 bet_amount = 4;</code>
     */
    protected $bet_amount = 0;
    /**
     * Generated from protobuf field <code>string bonus_type = 5;</code>
     */
    protected $bonus_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *           JOIN_ROOM, LEAVE_ROOM, SPIN, BUY_BONUS
     *     @type string $player_id
     *     @type string $room_id
     *     @type int|string $bet_amount
     *     @type string $bonus_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlotGame::initOnce();
        parent::__construct($data);
    }

    /**
     * JOIN_ROOM, LEAVE_ROOM, SPIN, BUY_BONUS
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * JOIN_ROOM, LEAVE_ROOM, SPIN, BUY_BONUS
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string player_id = 2;</code>
     * @return string
     */
    public function getPlayerId()
    {
        return $this->player_id;
    }

    /**
     * Generated from protobuf field <code>string player_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPlayerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->player_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string room_id = 3;</code>
     * @return string
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * Generated from protobuf field <code>string room_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkString($var, True);
        $this->room_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 bet_amount = 4;</code>
     * @return int|string
     */
    public function getBetAmount()
    {
        return $this->bet_amount;
    }

    /**
     * Generated from protobuf field <code>int64 bet_amount = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBetAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->bet_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bonus_type = 5;</code>
     * @return string
     */
    public function getBonusType()
    {
        return $this->bonus_type;
    }

    /**
     * Generated from protobuf field <code>string bonus_type = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBonusType($var)
    {
        GPBUtil::checkString($var, True);
        $this->bonus_type = $var;

        return $this;
    }

}

