<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SlotGame.proto

namespace Slot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 玩家信息
 *
 * Generated from protobuf message <code>slot.Player</code>
 */
class Player extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string player_id = 1;</code>
     */
    protected $player_id = '';
    /**
     * Generated from protobuf field <code>string player_name = 2;</code>
     */
    protected $player_name = '';
    /**
     * Generated from protobuf field <code>int64 balance = 3;</code>
     */
    protected $balance = 0;
    /**
     * Generated from protobuf field <code>int32 level = 4;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>int64 experience = 5;</code>
     */
    protected $experience = 0;
    /**
     * Generated from protobuf field <code>int64 last_login_time = 6;</code>
     */
    protected $last_login_time = 0;
    /**
     * Generated from protobuf field <code>int64 created_time = 7;</code>
     */
    protected $created_time = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $player_id
     *     @type string $player_name
     *     @type int|string $balance
     *     @type int $level
     *     @type int|string $experience
     *     @type int|string $last_login_time
     *     @type int|string $created_time
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlotGame::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string player_id = 1;</code>
     * @return string
     */
    public function getPlayerId()
    {
        return $this->player_id;
    }

    /**
     * Generated from protobuf field <code>string player_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlayerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->player_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string player_name = 2;</code>
     * @return string
     */
    public function getPlayerName()
    {
        return $this->player_name;
    }

    /**
     * Generated from protobuf field <code>string player_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPlayerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->player_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 balance = 3;</code>
     * @return int|string
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     * Generated from protobuf field <code>int64 balance = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkInt64($var);
        $this->balance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 level = 4;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>int32 level = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 experience = 5;</code>
     * @return int|string
     */
    public function getExperience()
    {
        return $this->experience;
    }

    /**
     * Generated from protobuf field <code>int64 experience = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExperience($var)
    {
        GPBUtil::checkInt64($var);
        $this->experience = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 last_login_time = 6;</code>
     * @return int|string
     */
    public function getLastLoginTime()
    {
        return $this->last_login_time;
    }

    /**
     * Generated from protobuf field <code>int64 last_login_time = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastLoginTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_login_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 created_time = 7;</code>
     * @return int|string
     */
    public function getCreatedTime()
    {
        return $this->created_time;
    }

    /**
     * Generated from protobuf field <code>int64 created_time = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->created_time = $var;

        return $this;
    }

}

