<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SlotGame.proto

namespace Slot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 房间信息
 *
 * Generated from protobuf message <code>slot.Room</code>
 */
class Room extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string room_id = 1;</code>
     */
    protected $room_id = '';
    /**
     * Generated from protobuf field <code>string room_name = 2;</code>
     */
    protected $room_name = '';
    /**
     * Generated from protobuf field <code>int32 max_players = 3;</code>
     */
    protected $max_players = 0;
    /**
     * Generated from protobuf field <code>int32 current_players = 4;</code>
     */
    protected $current_players = 0;
    /**
     * Generated from protobuf field <code>int64 min_bet = 5;</code>
     */
    protected $min_bet = 0;
    /**
     * Generated from protobuf field <code>int64 max_bet = 6;</code>
     */
    protected $max_bet = 0;
    /**
     * waiting, playing, closed
     *
     * Generated from protobuf field <code>string status = 7;</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $room_id
     *     @type string $room_name
     *     @type int $max_players
     *     @type int $current_players
     *     @type int|string $min_bet
     *     @type int|string $max_bet
     *     @type string $status
     *           waiting, playing, closed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlotGame::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string room_id = 1;</code>
     * @return string
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * Generated from protobuf field <code>string room_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkString($var, True);
        $this->room_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string room_name = 2;</code>
     * @return string
     */
    public function getRoomName()
    {
        return $this->room_name;
    }

    /**
     * Generated from protobuf field <code>string room_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomName($var)
    {
        GPBUtil::checkString($var, True);
        $this->room_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_players = 3;</code>
     * @return int
     */
    public function getMaxPlayers()
    {
        return $this->max_players;
    }

    /**
     * Generated from protobuf field <code>int32 max_players = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxPlayers($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_players = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 current_players = 4;</code>
     * @return int
     */
    public function getCurrentPlayers()
    {
        return $this->current_players;
    }

    /**
     * Generated from protobuf field <code>int32 current_players = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentPlayers($var)
    {
        GPBUtil::checkInt32($var);
        $this->current_players = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 min_bet = 5;</code>
     * @return int|string
     */
    public function getMinBet()
    {
        return $this->min_bet;
    }

    /**
     * Generated from protobuf field <code>int64 min_bet = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinBet($var)
    {
        GPBUtil::checkInt64($var);
        $this->min_bet = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 max_bet = 6;</code>
     * @return int|string
     */
    public function getMaxBet()
    {
        return $this->max_bet;
    }

    /**
     * Generated from protobuf field <code>int64 max_bet = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxBet($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_bet = $var;

        return $this;
    }

    /**
     * waiting, playing, closed
     *
     * Generated from protobuf field <code>string status = 7;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * waiting, playing, closed
     *
     * Generated from protobuf field <code>string status = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

}

