<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SlotGame.proto

namespace Slot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 服务端消息
 *
 * Generated from protobuf message <code>slot.ServerMessage</code>
 */
class ServerMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * ROOM_UPDATE, PLAYER_UPDATE, SPIN_RESULT, ERROR
     *
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>.slot.Room room = 2;</code>
     */
    protected $room = null;
    /**
     * Generated from protobuf field <code>.slot.Player player = 3;</code>
     */
    protected $player = null;
    /**
     * Generated from protobuf field <code>.slot.SpinResult spin_result = 4;</code>
     */
    protected $spin_result = null;
    /**
     * Generated from protobuf field <code>string error_message = 5;</code>
     */
    protected $error_message = '';
    /**
     * Generated from protobuf field <code>repeated .slot.Room available_rooms = 6;</code>
     */
    private $available_rooms;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *           ROOM_UPDATE, PLAYER_UPDATE, SPIN_RESULT, ERROR
     *     @type \Slot\Room $room
     *     @type \Slot\Player $player
     *     @type \Slot\SpinResult $spin_result
     *     @type string $error_message
     *     @type array<\Slot\Room>|\Google\Protobuf\Internal\RepeatedField $available_rooms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlotGame::initOnce();
        parent::__construct($data);
    }

    /**
     * ROOM_UPDATE, PLAYER_UPDATE, SPIN_RESULT, ERROR
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * ROOM_UPDATE, PLAYER_UPDATE, SPIN_RESULT, ERROR
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.slot.Room room = 2;</code>
     * @return \Slot\Room|null
     */
    public function getRoom()
    {
        return $this->room;
    }

    public function hasRoom()
    {
        return isset($this->room);
    }

    public function clearRoom()
    {
        unset($this->room);
    }

    /**
     * Generated from protobuf field <code>.slot.Room room = 2;</code>
     * @param \Slot\Room $var
     * @return $this
     */
    public function setRoom($var)
    {
        GPBUtil::checkMessage($var, \Slot\Room::class);
        $this->room = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.slot.Player player = 3;</code>
     * @return \Slot\Player|null
     */
    public function getPlayer()
    {
        return $this->player;
    }

    public function hasPlayer()
    {
        return isset($this->player);
    }

    public function clearPlayer()
    {
        unset($this->player);
    }

    /**
     * Generated from protobuf field <code>.slot.Player player = 3;</code>
     * @param \Slot\Player $var
     * @return $this
     */
    public function setPlayer($var)
    {
        GPBUtil::checkMessage($var, \Slot\Player::class);
        $this->player = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.slot.SpinResult spin_result = 4;</code>
     * @return \Slot\SpinResult|null
     */
    public function getSpinResult()
    {
        return $this->spin_result;
    }

    public function hasSpinResult()
    {
        return isset($this->spin_result);
    }

    public function clearSpinResult()
    {
        unset($this->spin_result);
    }

    /**
     * Generated from protobuf field <code>.slot.SpinResult spin_result = 4;</code>
     * @param \Slot\SpinResult $var
     * @return $this
     */
    public function setSpinResult($var)
    {
        GPBUtil::checkMessage($var, \Slot\SpinResult::class);
        $this->spin_result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error_message = 5;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Generated from protobuf field <code>string error_message = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .slot.Room available_rooms = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAvailableRooms()
    {
        return $this->available_rooms;
    }

    /**
     * Generated from protobuf field <code>repeated .slot.Room available_rooms = 6;</code>
     * @param array<\Slot\Room>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAvailableRooms($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Slot\Room::class);
        $this->available_rooms = $arr;

        return $this;
    }

}

