<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SlotGame.proto

namespace Slot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 旋转结果
 *
 * Generated from protobuf message <code>slot.SpinResult</code>
 */
class SpinResult extends \Google\Protobuf\Internal\Message
{
    /**
     * 3x5 的符号矩阵
     *
     * Generated from protobuf field <code>repeated string reels = 1;</code>
     */
    private $reels;
    /**
     * Generated from protobuf field <code>int64 win_amount = 2;</code>
     */
    protected $win_amount = 0;
    /**
     * Generated from protobuf field <code>repeated .slot.WinLine win_lines = 3;</code>
     */
    private $win_lines;
    /**
     * Generated from protobuf field <code>bool is_bonus = 4;</code>
     */
    protected $is_bonus = false;
    /**
     * Generated from protobuf field <code>int64 new_balance = 5;</code>
     */
    protected $new_balance = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $reels
     *           3x5 的符号矩阵
     *     @type int|string $win_amount
     *     @type array<\Slot\WinLine>|\Google\Protobuf\Internal\RepeatedField $win_lines
     *     @type bool $is_bonus
     *     @type int|string $new_balance
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlotGame::initOnce();
        parent::__construct($data);
    }

    /**
     * 3x5 的符号矩阵
     *
     * Generated from protobuf field <code>repeated string reels = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReels()
    {
        return $this->reels;
    }

    /**
     * 3x5 的符号矩阵
     *
     * Generated from protobuf field <code>repeated string reels = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->reels = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 win_amount = 2;</code>
     * @return int|string
     */
    public function getWinAmount()
    {
        return $this->win_amount;
    }

    /**
     * Generated from protobuf field <code>int64 win_amount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWinAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->win_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .slot.WinLine win_lines = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWinLines()
    {
        return $this->win_lines;
    }

    /**
     * Generated from protobuf field <code>repeated .slot.WinLine win_lines = 3;</code>
     * @param array<\Slot\WinLine>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWinLines($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Slot\WinLine::class);
        $this->win_lines = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_bonus = 4;</code>
     * @return bool
     */
    public function getIsBonus()
    {
        return $this->is_bonus;
    }

    /**
     * Generated from protobuf field <code>bool is_bonus = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsBonus($var)
    {
        GPBUtil::checkBool($var);
        $this->is_bonus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 new_balance = 5;</code>
     * @return int|string
     */
    public function getNewBalance()
    {
        return $this->new_balance;
    }

    /**
     * Generated from protobuf field <code>int64 new_balance = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNewBalance($var)
    {
        GPBUtil::checkInt64($var);
        $this->new_balance = $var;

        return $this;
    }

}

