<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SlotGame.proto

namespace Slot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 老虎机符号
 *
 * Generated from protobuf message <code>slot.Symbol</code>
 */
class Symbol extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string symbol_id = 1;</code>
     */
    protected $symbol_id = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int32 weight = 3;</code>
     */
    protected $weight = 0;
    /**
     * Generated from protobuf field <code>int32 multiplier = 4;</code>
     */
    protected $multiplier = 0;
    /**
     * Generated from protobuf field <code>bool is_wild = 5;</code>
     */
    protected $is_wild = false;
    /**
     * Generated from protobuf field <code>bool is_scatter = 6;</code>
     */
    protected $is_scatter = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $symbol_id
     *     @type string $name
     *     @type int $weight
     *     @type int $multiplier
     *     @type bool $is_wild
     *     @type bool $is_scatter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlotGame::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string symbol_id = 1;</code>
     * @return string
     */
    public function getSymbolId()
    {
        return $this->symbol_id;
    }

    /**
     * Generated from protobuf field <code>string symbol_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSymbolId($var)
    {
        GPBUtil::checkString($var, True);
        $this->symbol_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 weight = 3;</code>
     * @return int
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>int32 weight = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 multiplier = 4;</code>
     * @return int
     */
    public function getMultiplier()
    {
        return $this->multiplier;
    }

    /**
     * Generated from protobuf field <code>int32 multiplier = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMultiplier($var)
    {
        GPBUtil::checkInt32($var);
        $this->multiplier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_wild = 5;</code>
     * @return bool
     */
    public function getIsWild()
    {
        return $this->is_wild;
    }

    /**
     * Generated from protobuf field <code>bool is_wild = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsWild($var)
    {
        GPBUtil::checkBool($var);
        $this->is_wild = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_scatter = 6;</code>
     * @return bool
     */
    public function getIsScatter()
    {
        return $this->is_scatter;
    }

    /**
     * Generated from protobuf field <code>bool is_scatter = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsScatter($var)
    {
        GPBUtil::checkBool($var);
        $this->is_scatter = $var;

        return $this;
    }

}

