<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SlotGame.proto

namespace Slot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 赢钱线路
 *
 * Generated from protobuf message <code>slot.WinLine</code>
 */
class WinLine extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 line_index = 1;</code>
     */
    protected $line_index = 0;
    /**
     * Generated from protobuf field <code>string symbol = 2;</code>
     */
    protected $symbol = '';
    /**
     * Generated from protobuf field <code>int32 count = 3;</code>
     */
    protected $count = 0;
    /**
     * Generated from protobuf field <code>int64 amount = 4;</code>
     */
    protected $amount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $line_index
     *     @type string $symbol
     *     @type int $count
     *     @type int|string $amount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SlotGame::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 line_index = 1;</code>
     * @return int
     */
    public function getLineIndex()
    {
        return $this->line_index;
    }

    /**
     * Generated from protobuf field <code>int32 line_index = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLineIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->line_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string symbol = 2;</code>
     * @return string
     */
    public function getSymbol()
    {
        return $this->symbol;
    }

    /**
     * Generated from protobuf field <code>string symbol = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSymbol($var)
    {
        GPBUtil::checkString($var, True);
        $this->symbol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 count = 3;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int32 count = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 4;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

}

