<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 战斗动作
 *
 * Generated from protobuf message <code>game.BattleAction</code>
 */
class BattleAction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string playerId = 1;</code>
     */
    protected $playerId = '';
    /**
     * Generated from protobuf field <code>string action = 2;</code>
     */
    protected $action = '';
    /**
     * Generated from protobuf field <code>string targetId = 3;</code>
     */
    protected $targetId = '';
    /**
     * Generated from protobuf field <code>uint32 value = 4;</code>
     */
    protected $value = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $playerId
     *     @type string $action
     *     @type string $targetId
     *     @type int $value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Game::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string playerId = 1;</code>
     * @return string
     */
    public function getPlayerId()
    {
        return $this->playerId;
    }

    /**
     * Generated from protobuf field <code>string playerId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlayerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->playerId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string action = 2;</code>
     * @return string
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>string action = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string targetId = 3;</code>
     * @return string
     */
    public function getTargetId()
    {
        return $this->targetId;
    }

    /**
     * Generated from protobuf field <code>string targetId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetId($var)
    {
        GPBUtil::checkString($var, True);
        $this->targetId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 value = 4;</code>
     * @return int
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>uint32 value = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkUint32($var);
        $this->value = $var;

        return $this;
    }

}

