<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 玩家状态
 *
 * Generated from protobuf message <code>game.Player</code>
 */
class Player extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>uint32 hp = 3;</code>
     */
    protected $hp = 0;
    /**
     * Generated from protobuf field <code>uint32 maxHp = 4;</code>
     */
    protected $maxHp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $name
     *     @type int $hp
     *     @type int $maxHp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Game::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 hp = 3;</code>
     * @return int
     */
    public function getHp()
    {
        return $this->hp;
    }

    /**
     * Generated from protobuf field <code>uint32 hp = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setHp($var)
    {
        GPBUtil::checkUint32($var);
        $this->hp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 maxHp = 4;</code>
     * @return int
     */
    public function getMaxHp()
    {
        return $this->maxHp;
    }

    /**
     * Generated from protobuf field <code>uint32 maxHp = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxHp($var)
    {
        GPBUtil::checkUint32($var);
        $this->maxHp = $var;

        return $this;
    }

}

