<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 房间信息
 *
 * Generated from protobuf message <code>game.Room</code>
 */
class Room extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>repeated .game.Player players = 2;</code>
     */
    private $players;
    /**
     * Generated from protobuf field <code>string current_turn = 3;</code>
     */
    protected $current_turn = '';
    /**
     * Generated from protobuf field <code>string status = 4;</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type array<\Game\Player>|\Google\Protobuf\Internal\RepeatedField $players
     *     @type string $current_turn
     *     @type string $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Game::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .game.Player players = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPlayers()
    {
        return $this->players;
    }

    /**
     * Generated from protobuf field <code>repeated .game.Player players = 2;</code>
     * @param array<\Game\Player>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPlayers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Game\Player::class);
        $this->players = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string current_turn = 3;</code>
     * @return string
     */
    public function getCurrentTurn()
    {
        return $this->current_turn;
    }

    /**
     * Generated from protobuf field <code>string current_turn = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrentTurn($var)
    {
        GPBUtil::checkString($var, True);
        $this->current_turn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 4;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

}

