<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Game.proto

namespace Game;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 服务端下行消息
 *
 * Generated from protobuf message <code>game.ServerMessage</code>
 */
class ServerMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>repeated .game.Player players = 2;</code>
     */
    private $players;
    /**
     * Generated from protobuf field <code>string result = 3;</code>
     */
    protected $result = '';
    /**
     * Generated from protobuf field <code>.game.Player player = 4;</code>
     */
    protected $player = null;
    /**
     * 新增字段，指示当前接收消息的玩家是否轮到
     *
     * Generated from protobuf field <code>bool is_my_turn = 5;</code>
     */
    protected $is_my_turn = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *     @type array<\Game\Player>|\Google\Protobuf\Internal\RepeatedField $players
     *     @type string $result
     *     @type \Game\Player $player
     *     @type bool $is_my_turn
     *           新增字段，指示当前接收消息的玩家是否轮到
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Game::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .game.Player players = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPlayers()
    {
        return $this->players;
    }

    /**
     * Generated from protobuf field <code>repeated .game.Player players = 2;</code>
     * @param array<\Game\Player>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPlayers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Game\Player::class);
        $this->players = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string result = 3;</code>
     * @return string
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>string result = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkString($var, True);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.game.Player player = 4;</code>
     * @return \Game\Player|null
     */
    public function getPlayer()
    {
        return $this->player;
    }

    public function hasPlayer()
    {
        return isset($this->player);
    }

    public function clearPlayer()
    {
        unset($this->player);
    }

    /**
     * Generated from protobuf field <code>.game.Player player = 4;</code>
     * @param \Game\Player $var
     * @return $this
     */
    public function setPlayer($var)
    {
        GPBUtil::checkMessage($var, \Game\Player::class);
        $this->player = $var;

        return $this;
    }

    /**
     * 新增字段，指示当前接收消息的玩家是否轮到
     *
     * Generated from protobuf field <code>bool is_my_turn = 5;</code>
     * @return bool
     */
    public function getIsMyTurn()
    {
        return $this->is_my_turn;
    }

    /**
     * 新增字段，指示当前接收消息的玩家是否轮到
     *
     * Generated from protobuf field <code>bool is_my_turn = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsMyTurn($var)
    {
        GPBUtil::checkBool($var);
        $this->is_my_turn = $var;

        return $this;
    }

}

