<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Game.proto

namespace GPBMetadata;

class Game
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
È

Game.protogame"=
Player

id (	
name (	

hp (
maxHp ("W
Room

id (	
players (2.game.Player
current_turn (	
status (	"Q
BattleAction
playerId (	
action (	
targetId (	
value ("A
ClientMessage
type (	"
action (2.game.BattleAction"~
ServerMessage
type (	
players (2.game.Player
result (	
player (2.game.Player

is_my_turn (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

