<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SlotGame.proto

namespace GPBMetadata;

class SlotGame
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
£
SlotGame.protoslot"“
Player
	player_id (	
player_name (	
balance (
level (

experience (
last_login_time (
created_time ("r
Symbol
	symbol_id (	
name (	
weight (

multiplier (
is_wild (

is_scatter ("x

SpinResult
reels (	

win_amount ( 
	win_lines (2.slot.WinLine
is_bonus (
new_balance ("L
WinLine

line_index (
symbol (	
count (
amount ("Š
Room
room_id (	
	room_name (	
max_players (
current_players (
min_bet (
max_bet (
status (	"i
ClientMessage
type (	
	player_id (	
room_id (	

bet_amount (

bonus_type (	"¸
ServerMessage
type (	
room (2
.slot.Room
player (2.slot.Player%
spin_result (2.slot.SpinResult
error_message (	#
available_rooms (2
.slot.Roombproto3'
        , true);

        static::$is_initialized = true;
    }
}

